platform:ios,'8.0'
target 'Naidean' do
pod 'AFNetworking', '~>3.1.0'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MBProgressHUD+JDragon'
pod 'MJRefresh'
pod 'MJExtension'
pod 'JPush'
pod 'YYKit'
#pod 'Xg-Push-SDK-iOS-3.1.1'
end
